
serenity.project.name=PruebasRapiCredit
webdriver.driver=firefox
serenity.browser=firefox
serenity.driver=firefox
serenity.driver.capabilities.args=--width=1920 --height=1080
serenity.headless=false
webdriver.gecko.driver=src/test/resources/geckodriver/geckodriver.exe
serenity.headless.mode=false
serenity.timeout.implicitlyWait=5
serenity.outputDirectory = target/site/serenity
serenity.take.screenshots = FOR_FAILURES
serenity.aggregate.timeout = 300

